name: Deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install node modules
        run: npm install
      - name: Create env file
        run: |
          touch .env
          echo CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} >> .env
          echo CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }} >> .env
          echo GOOGLE_ANALYTICS_TRACKING_ID=${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }} >> .env
      - name: Build application
        run: npm run build
      - name: Deploy application
        run: npm run deploy -- -r https://${{ secrets.GH_TOKEN }}@github.com/LeeBrooks3/LeeBrooks3.github.io.git
